colibri/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from tastypie.api import Api

from commission.api import CommissionManagerResource
from initiatives.api import InitiativeResource
from member.api import MemberResource
from parliamentarygroup.api import GroupResource,\
                                   GroupManagerResource,\
                                   GroupMemberResource,\
                                   PartyResource
from vote.api import VotingResource, VoteResource, SessionResource,\
                     VotingFullResource, VoteFullResource

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(CommissionManagerResource())
v1_api.register(GroupManagerResource())
v1_api.register(GroupMemberResource())
v1_api.register(GroupResource())
v1_api.register(InitiativeResource())
v1_api.register(MemberResource())
v1_api.register(PartyResource())
v1_api.register(SessionResource())
v1_api.register(VoteFullResource())
v1_api.register(VoteResource())
v1_api.register(VotingFullResource())
v1_api.register(VotingResource())

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'documentacion/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    url(r'^api/', include(v1_api.urls)),
    url(r'accounts/', include('allauth.urls')),
 #   url(r'^stats/', include('stats.urls')),
    url(r'^apps/$','main.views.apps', name="main_apps"),
    url(r'^somos/$','main.views.weare', name="main_weare"),
    url(r'^gracias/$','main.views.thanks', name="main_thanks"),
    url(r'^accounts/profile/$',
        TemplateView.as_view(template_name="dataminers/profile.html")),
    url(r'^$','main.views.index', name="main_index"),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
)

stats/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('stats.views',
        url(r'^$', 'stats', name='stats'),
)

tastypie_swagger/urls.py
try:
	from django.conf.urls import patterns, include, url
except ImportError:
	from django.conf.urls.defaults import patterns, include, url

from .views import SwaggerView, ResourcesView, SchemaView

urlpatterns = patterns('',
    url(r'^$', SwaggerView.as_view(), name='documentation'),
    url(r'^resources/$', ResourcesView.as_view(), name='resources'),
    url(r'^schema/(?P<resource>\S+)/$', SchemaView.as_view()),
    url(r'^schema/$', SchemaView.as_view(), name='schema'),
)

tastypie_swagger/views.py
import sys
import json

from django.views.generic import TemplateView
from django.http import HttpResponse, Http404
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse
from django.conf import settings

from .mapping import ResourceSwaggerMapping


class TastypieApiMixin(object):
    """
    Provides views with a 'tastypie_api' attr representing a tastypie.api.Api instance

    Python path must be defined in settings as TASTYPIE_SWAGGER_API_MODULE
    """
    def __init__(self, *args, **kwargs):
        super(TastypieApiMixin, self).__init__(*args, **kwargs)
        tastypie_api_module = getattr(settings, 'TASTYPIE_SWAGGER_API_MODULE', None)
        if not tastypie_api_module:
            raise ImproperlyConfigured("Must define TASTYPIE_SWAGGER_API_MODULE in settings as path to a tastypie.api.Api instance")
        path, attr = tastypie_api_module.rsplit('.', 1)
        try:
            tastypie_api = getattr(sys.modules[path], attr, None)
        except KeyError:
            raise ImproperlyConfigured("%s is not a valid python path" % path)
        if not tastypie_api:
            raise ImproperlyConfigured("%s is not a valid tastypie.api.Api instance" % tastypie_api_module)
        self.tastypie_api = tastypie_api


class SwaggerApiDataMixin(object):
    """
    Provides required API context data
    """

    def get_context_data(self, *args, **kwargs):
        context = super(SwaggerApiDataMixin, self).get_context_data(*args, **kwargs)
        context.update({
            # TODO: How should versions be controlled?
            'apiVersion': '0.1',
            'swaggerVersion': '1.1',
        })
        return context


class JSONView(TemplateView):
    """
    Simple JSON rendering
    """
    response_class = HttpResponse

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response with a template rendered with the given context.
        """
        for k in ['params','view']:
            if k in context:
                del context[k]
        return self.response_class(
            json.dumps(context),
            content_type='application/json',
            **response_kwargs
        )


class SwaggerView(TastypieApiMixin, TemplateView):
    """
    Display the swagger-ui page
    """

    template_name = 'tastypie_swagger/index.html'


class ResourcesView(TastypieApiMixin, SwaggerApiDataMixin, JSONView):
    """
    Provide a top-level resource listing for swagger

    This JSON must conform to https://github.com/wordnik/swagger-core/wiki/Resource-Listing
    """

    def get_context_data(self, *args, **kwargs):
        context = super(ResourcesView, self).get_context_data(*args, **kwargs)

        # Construct schema endpoints from resources
        apis = [{'path': '/%s' % name} for name in sorted(self.tastypie_api._registry.keys())]
        context.update({
            'basePath': self.request.build_absolute_uri(reverse('tastypie_swagger:schema')),
            'apis': apis,
        })
        return context


class SchemaView(TastypieApiMixin, SwaggerApiDataMixin, JSONView):
    """
    Provide an individual resource schema for swagger

    This JSON must conform to https://github.com/wordnik/swagger-core/wiki/API-Declaration
    """

    def get_context_data(self, *args, **kwargs):
        # Verify matching tastypie resource exists
        resource_name = kwargs.get('resource', None)
        if not resource_name in self.tastypie_api._registry:
            raise Http404

        # Generate mapping from tastypie.resources.Resource.build_schema
        resource = self.tastypie_api._registry.get(resource_name)
        mapping = ResourceSwaggerMapping(resource)

        context = super(SchemaView, self).get_context_data(*args, **kwargs)
        context.update({
            'basePath': '/',
            'apis': mapping.build_apis(),
            'models': mapping.build_models()
        })
        return context

tastypie_swagger/templates/tastypie_swagger/index.html
{% extends "base.html" %}
{% load url from future %}

{% block links %}
    {{ block.super }}
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'/>
    <link href='{{ STATIC_URL }}tastypie_swagger/css/hightlight.default.css' media='screen' rel='stylesheet' type='text/css'/>
    <link href='{{ STATIC_URL }}tastypie_swagger/css/screen.css' media='screen' rel='stylesheet' type='text/css'/>
{% endblock %}
{% block scripts %}
    {{ block.super  }}
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/jquery-1.8.0.min.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/jquery.slideto.min.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/jquery.wiggle.min.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/jquery.ba-bbq.min.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/handlebars-1.0.rc.1.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/underscore-min.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/backbone-min.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/swagger.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/swagger-ui.js' type='text/javascript'></script>
    <script src='{{ STATIC_URL }}tastypie_swagger/js/lib/highlight.7.3.pack.js' type='text/javascript'></script>

    <style type="text/css">
        .swagger-ui-wrap {
            max-width: 960px;
            margin-left: auto;
            margin-right: auto;
        }

        .icon-btn {
            cursor: pointer;
        }

        #message-bar {
            min-height: 30px;
            text-align: center;
            padding-top: 10px;
        }

        .message-success {
            color: #89BF04;
        }

        .message-fail {
            color: #cc0000;
        }
    </style>

    <script type="text/javascript">
        $(function () {
            window.swaggerUi = new SwaggerUi({
                discoveryUrl:"{% url 'tastypie_swagger:resources' %}",
                apiKey:"special-key",
                dom_id:"swagger-ui-container",
                supportHeaderParams: false,
                supportedSubmitMethods: ['get', 'post', 'put'],
                onComplete: function(swaggerApi, swaggerUi){
                    $("img[src$='throbber.gif']").attr("src", "{{ STATIC_URL }}tastypie_swagger/images/throbber.gif");
                    if(console) {
                        console.log("Loaded SwaggerUI")
                        console.log(swaggerApi);
                        console.log(swaggerUi);
                    }
                    $('pre code').each(function(i, e) {hljs.highlightBlock(e)});
                },
                onFailure: function(data) {
                    if(console) {
                        console.log("Unable to Load SwaggerUI");
                        console.log(data);
                    }
                },
                docExpansion: "none"
            });

            window.swaggerUi.load();
        });

      </script>
{% endblock %}

{% block content %}

<div id="message-bar" class="swagger-ui-wrap">
    &nbsp;
</div>

<div id="swagger-ui-container" class="swagger-ui-wrap">

</div>
{% endblock %}