colibri/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from tastypie.api import Api

from commission.api import CommissionManagerResource
from initiatives.api import InitiativeResource
from member.api import MemberResource
from parliamentarygroup.api import GroupResource,\
                                   GroupManagerResource,\
                                   GroupMemberResource,\
                                   PartyResource
from vote.api import VotingResource, VoteResource, SessionResource,\
                     VotingFullResource, VoteFullResource

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(CommissionManagerResource())
v1_api.register(GroupManagerResource())
v1_api.register(GroupMemberResource())
v1_api.register(GroupResource())
v1_api.register(InitiativeResource())
v1_api.register(MemberResource())
v1_api.register(PartyResource())
v1_api.register(SessionResource())
v1_api.register(VoteFullResource())
v1_api.register(VoteResource())
v1_api.register(VotingFullResource())
v1_api.register(VotingResource())

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'documentacion/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    url(r'^api/', include(v1_api.urls)),
    url(r'accounts/', include('allauth.urls')),
 #   url(r'^stats/', include('stats.urls')),
    url(r'^apps/$','main.views.apps', name="main_apps"),
    url(r'^somos/$','main.views.weare', name="main_weare"),
    url(r'^gracias/$','main.views.thanks', name="main_thanks"),
    url(r'^accounts/profile/$',
        TemplateView.as_view(template_name="dataminers/profile.html")),
    url(r'^$','main.views.index', name="main_index"),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
)

stats/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('stats.views',
        url(r'^$', 'stats', name='stats'),
)

stats/models.py
from socket import gethostbyaddr

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from stats.managers import RequestManager
from stats.utils import HTTP_STATUS_CODES, browsers, engines
from stats import settings

class Request(models.Model):
    # Response infomation
    response = models.SmallIntegerField(_('response'), choices=HTTP_STATUS_CODES, default=200)

    # Request infomation
    method = models.CharField(_('method'), default='GET', max_length=7)
    path = models.CharField(_('path'), max_length=255)
    time = models.DateTimeField(_('time'), auto_now_add=True)
    parameters = models.TextField(_('parameters'), blank=True, null=True)

    is_secure = models.BooleanField(_('is secure'), default=False)
    is_ajax = models.BooleanField(_('is ajax'), default=False, help_text=_('Wheather this request was used via javascript.'))

    # User infomation
    ip = models.IPAddressField(_('ip address'))
    user = models.ForeignKey(User, blank=True, null=True, verbose_name=_('user'))
    referer = models.URLField(_('referer'), max_length=255, blank=True, null=True)
    user_agent = models.CharField(_('user agent'), max_length=255, blank=True, null=True)
    language = models.CharField(_('language'), max_length=255, blank=True, null=True)

    objects = RequestManager()

    class Meta:
        verbose_name = _('request')
        verbose_name_plural = _('requests')
        ordering = ('-time',)

    def __unicode__(self):
        return u'[%s] %s %s %s' % (self.time, self.method, self.path, self.response)

    def get_user(self):
        return User.objects.get(pk=self.user_id)

    def from_http_request(self, request, response=None, commit=True):
        # Request infomation
        self.method = request.method
        self.path = request.path

        self.is_secure = request.is_secure()
        self.is_ajax = request.is_ajax()

        self.parameters = ''
        if request.GET:
            for item in request.GET.iteritems():
                self.parameters += ': '.join(item) + ' | '

        # User infomation
        self.ip = request.META.get('REMOTE_ADDR', '')
        self.referer = request.META.get('HTTP_REFERER', '')[:255]
        self.user_agent = request.META.get('HTTP_USER_AGENT', '')[:255]
        self.language = request.META.get('HTTP_ACCEPT_LANGUAGE', '')[:255]

        if getattr(request, 'user', False):
            if request.user.is_authenticated():
                self.user = request.user

        if response:
            self.response = response.status_code

            if (response.status_code == 301) or (response.status_code == 302):
                self.redirect = response['Location']

        if commit:
            self.save()

    #@property
    def browser(self):
        if not self.user_agent:
            return

        if not hasattr(self, '_browser'):
            self._browser = browsers.resolve(self.user_agent)
        return self._browser[0]
    browser = property(browser)

    #@property
    def keywords(self):
        if not self.referer:
            return

        if not hasattr(self, '_keywords'):
            self._keywords = engines.resolve(self.referer)
        if self._keywords:
            return ' '.join(self._keywords[1]['keywords'].split('+'))
    keywords = property(keywords)

    #@property
    def hostname(self):
        try:
            return gethostbyaddr(self.ip)[0]
        except Exception:  # socket.gaierror, socket.herror, etc
            return self.ip
    hostname = property(hostname)

    def save(self, *args, **kwargs):
        if not settings.REQUEST_LOG_IP:
            self.ip = settings.REQUEST_IP_DUMMY
        elif settings.REQUEST_ANONYMOUS_IP:
            parts = self.ip.split('.')[0:-1]
            parts.append('1')
            self.ip='.'.join(parts)
        if not settings.REQUEST_LOG_USER:
            self.user = None

        super(Request, self).save(*args, **kwargs)

stats/views.py
from django.shortcuts import render

from stats.models import Request
from stats.plugins import LatestRequests


def index(request):
    params = {}
    return render(request, 'main/index.html', params)

stats/templates/request/plugins/activeusers.html
{% extends "request/plugins/table.html" %}
{% load i18n %}

{% block table %}
    <tr>
        <th>{% trans "User" %}</th>
    </tr>
    
  {% load request_tag %}
  {% active_users in 5 minutes as user_list %}
  {% for user in user_list %}
    <tr>
        <td><a href="{{ user.get_absolute_url}}">{{ user.username }}</a><td>
    </tr>
  {% endfor %}
{% endblock %}

stats/templates/request/plugins/base.html
<h2>{{ verbose_name }}</h2>
{% block plugin %}{% endblock %}

stats/templates/request/plugins/latestrequests.html
{% extends "request/plugins/table.html" %}
{% load i18n %}
{% load request_admin %}

{% block table %}
    <tr>
        <th>{% trans "Path" %}</th>
        <th>{% trans "From" %}</th>
        <th>{% trans "Response" %}</th>
        <th>{% trans "Time" %}</th>
    </tr>
    
  {% for request in requests %}
    <tr>
        <td><a href="../?path={{ request.path }}" title="{{ request.path }}">{{ request.path|trunc:"35" }}</a></td>
        <td>{% firstof request.get_user request.ip %}</td>
        <td>{{ request.get_response_display }}</td>
        <td><a href="../{{ request.id }}/"><abbr class="relatize" title="{{ request.time }}">{{ request.time|date:"D M d H:i:s O Y" }}</abbr></a></td>
    </tr>
  {% endfor %}
{% endblock %}

stats/templates/request/plugins/table.html
<table summary="{{ verbose_name }}" style="width: 100%;">
    <caption>{{ verbose_name }}</caption>
    {% block table %}{% endblock %}
</table>

stats/templates/request/plugins/topbrowsers.html
{% extends "request/plugins/base.html" %}

{% block plugin %}
    {% load request_admin %}
    <img src="{% pie_chart browsers 440 150 %}" />
{% endblock %}

stats/templates/request/plugins/toppaths.html
{% extends "request/plugins/table.html" %}
{% load i18n %}
{% load request_admin %}

{% block table %}
    <tr>
        <th>{% trans "Path" %}</th>
        <th>{% trans "Visits" %}</th>
    </tr>
    
  {% for path in paths %}
    <tr>
        <td><a href="../?path={{ path.path }}" title="{{ path.path }}">{{ path.path|trunc:"60" }}</a></td>
        <td>{{ path.path__count }}</td>
    </tr>
  {% endfor %}
{% endblock %}

stats/templates/request/plugins/topreferrers.html
{% extends "request/plugins/table.html" %}
{% load i18n %}
{% load request_admin %}

{% block table %}
    <tr>
        <th>{% trans "Referrer" %}</th>
        <th>{% trans "Visits" %}</th>
    </tr>
    
  {% for referer in referrers %}
    <tr>
        <td><a href="{{ referer.referer }}" title="{{ referer.referer }}">{{ referer.referer|trunc:"60" }}</a></td>
        <td>{{ referer.referer__count }}</td>
    </tr>
  {% endfor %}
{% endblock %}

stats/templates/request/plugins/topsearchphrases.html
{% extends "request/plugins/table.html" %}
{% load i18n %}
{% load request_admin %}

{% block table %}
    <tr>
        <th>{% trans "Phrase" %}</th>
        <th>{% trans "Visits" %}</th>
    </tr>
    
  {% for phrase,visits in phrases %}
    <tr>
        <td>{{ phrase|trunc:"60" }}</td>
        <td>{{ visits }}</td>
    </tr>
  {% endfor %}
{% endblock %}

stats/templates/request/plugins/trafficinformation.html
{% extends "request/plugins/table.html" %}
{% load i18n %}

{% block table %}
    <tr>
        <td>&nbsp;</td>
        <th>{% trans "Today" %}</th>
        <th>{% trans "This week" %}</th>
        <th>{% trans "This month" %}</th>
        <th>{% trans "This year" %}</th>
        <th>{% trans "Alltime" %}</th>
    <tr>
    
  {% for key,value in traffic %}
    <tr>
        <th>{{ key }}</th>
          {% for item in value %}
            <td>{{ item }}</td>
          {% endfor %}
        </tr>
  {% endfor %}
{% endblock %}