colibri/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from tastypie.api import Api

from commission.api import CommissionManagerResource
from initiatives.api import InitiativeResource
from member.api import MemberResource
from parliamentarygroup.api import GroupResource,\
                                   GroupManagerResource,\
                                   GroupMemberResource,\
                                   PartyResource
from vote.api import VotingResource, VoteResource, SessionResource,\
                     VotingFullResource, VoteFullResource

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(CommissionManagerResource())
v1_api.register(GroupManagerResource())
v1_api.register(GroupMemberResource())
v1_api.register(GroupResource())
v1_api.register(InitiativeResource())
v1_api.register(MemberResource())
v1_api.register(PartyResource())
v1_api.register(SessionResource())
v1_api.register(VoteFullResource())
v1_api.register(VoteResource())
v1_api.register(VotingFullResource())
v1_api.register(VotingResource())

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'documentacion/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    url(r'^api/', include(v1_api.urls)),
    url(r'accounts/', include('allauth.urls')),
 #   url(r'^stats/', include('stats.urls')),
    url(r'^apps/$','main.views.apps', name="main_apps"),
    url(r'^somos/$','main.views.weare', name="main_weare"),
    url(r'^gracias/$','main.views.thanks', name="main_thanks"),
    url(r'^accounts/profile/$',
        TemplateView.as_view(template_name="dataminers/profile.html")),
    url(r'^$','main.views.index', name="main_index"),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
)

stats/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('stats.views',
        url(r'^$', 'stats', name='stats'),
)

tastypie_swagger/urls.py
try:
	from django.conf.urls import patterns, include, url
except ImportError:
	from django.conf.urls.defaults import patterns, include, url

from .views import SwaggerView, ResourcesView, SchemaView

urlpatterns = patterns('',
    url(r'^$', SwaggerView.as_view(), name='documentation'),
    url(r'^resources/$', ResourcesView.as_view(), name='resources'),
    url(r'^schema/(?P<resource>\S+)/$', SchemaView.as_view()),
    url(r'^schema/$', SchemaView.as_view(), name='schema'),
)

main/views.py
from django.shortcuts import render

def index(request):
    params = {}
    return render(request, 'main/index.html', params)

def weare(request):
    params = {}
    return render(request, 'main/weare.html', params)

def thanks(request):
    params = {}
    return render(request, 'main/thanks.html', params)

def apps(request):
    params = {}
    return render(request, 'main/apps.html', params)

colibri/templates/main/apps.html
{% extends "base.html" %}
{% block content %}  
  <!-- <div class="row">
    <div class="nine columns centered">
      <p class="main-text center-text white-text">"Somos un pequeño equipo pero con muchas ganas de construir colectivamente"</p>
    </div>
  </div> -->
  
  <div class="row">
    <div class="twelve columns">
      <h1>Open Congreso <span class="radius secondary label">WebApp</span></h1>
      <p>Trabajo desarrollado por  <a href="https://twitter.com/a_ditoro">Andrea Di Toro</a></p>
      <a href="http://opencongreso.es/" target="_blank">Accede a la app</a>
    </div>
    <div class="twelve columns">
      <h1>Congreso al día <span class="radius secondary label">WebApp</span></h1>
      <p>Trabajo desarrollado por  <a href="http://about.me/rafaparadela">Rafa Paradela</a></p>
      <a href="https://github.com/rafaparadela/congresoaldia" target="_blank">Accede al código de la app</a>
    </div>
    <div class="twelve columns">
      <h1>PicaFlor <span class="radius secondary label">WindowsPhone</span></h1>
      <p>Trabajo desarrollado por  <a href="http://twitter.com/josemmortega">José Manuel Montero</a></p>
      <a href="http://www.windowsphone.com/es-es/store/app/picaflor/01df0c96-7cd2-4f61-af56-87d6b3cdfa64" target="_blank">Accede a la app</a>
    </div>
    <div class="twelve columns">
      <h1>PicaFlor <span class="radius secondary label">Windows8</span></h1>
      <p>Trabajo desarrollado por  <a href="http://twitter.com/josemmortega">José Manuel Montero</a></p>
      <a href="http://apps.microsoft.com/windows/es-es/app/picaflor/328352b0-6abe-4d6f-a4c7-fda567487857" target="_blank">Accede a la app</a>
    </div>
    <div class="twelve columns">
      <h1>ColibriBook <span class="radius secondary label">Android</span></h1>
      <p>Trabajo desarrollado por <a href="https://github.com/pulimento">Javier Pulido</a> y <a href="https://github.com/mjim79">Miguel J. Jiménez</a> con la colaboracion de <a href="http://edipotrebol.es">edipotrebol</a></p>
      <p>Identidad grafica desarrollada por <a href="http://lopezbesteiro.es">Ale Lopez Besteiro</a></p>
      <a href="https://play.google.com/store/apps/details?id=es.openkratio.colibribook" target="_blank">Accede a la app</a>
    </div>
    <div class="twelve columns">
      <h1>Espana 2012-2013 <span class="radius secondary label">WebApp</span></h1>
      <p>Trabajo desarrollado por  <a href="https://github.com/michalskop">Michal Skop</a></p>
      <a href="http://bl.ocks.org/michalskop/5773523" target="_blank">Accede a la app</a>
    </div>
  </div>
  

{% endblock %}

colibri/templates/main/documentation.html
{% extends "base.html" %}
{% block content %}
  <div class="row">
    <div class="ten columns centered">
    <h3>Documentacion</h3>
    <p>La API ha sido desarrollada con django-tastypie y los datos son servidos en JSON.</p>
    <p>La API esta formada por recursos; cada recurso es accesible a traves de la url http://proyectocolibri.es/api/v1/ seguido del nombre del recurso. Por ejemplo: http://proyectocolibri.es/api/v1/group/ , esto nos devolvera un JSON con todos los grupos parlamentarios y su informacion.</p>
    <p>En los distintos recursos se han habilitado diferentes campos por los que poder filtrar. Para ello se le pasa como argumento el campo por el que se quiere filtrar y el valor que se desea. Por ejemplo, en el recurso de los Grupos parlamentarios podemos filtrar por el nombre de la siguiente manera:<br /><br />
  <a href="http://proyectocolibri.es/api/v1/group/?id=1" target="_blank">http://proyectocolibri.es/api/v1/group/?id=1</a></p>
<br />
<br />

    <h3>Listado de Grupos parlamentarios</h3>
    <p>Este recurso nos devuelve los grupos parlamentarios que forman el congreso. En este recurso tambien obtenemos una relacion de los miembros que pertenecen a dicho partido.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/group/" target=_blank>http://proyectocolibri.es/api/v1/group/</a></td>
          <td>Campos para filtrar: 
            <a href="http://proyectocolibri.es/api/v1/group/?id=1" target=_blank>id</a>, 
            <a href="http://proyectocolibri.es/api/v1/group/?name=G.P. Popular" target=_blank>name</a>
          </td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/group/schema/">
        Detalle del recurso.
    </a>


    <h3>Listado de Partidos</h3>
    <p>Con este recurso obtenemos un listado de los distintos partidos politicos del Congreso.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/party/" target=_blank>http://proyectocolibri.es/api/v1/party/</a></td>
          <td>Campos para filtrar: 
            <a href="http://proyectocolibri.es/api/v1/party/?id=1" target=_blank>id</a>, 
            <a href="http://proyectocolibri.es/api/v1/party/?name=AMAIUR" target=_blank>name</a>
          </td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/party/schema/">
        Detalle del recurso.
    </a>

    <h3>Listado de Miembros</h3>
    <p>Con este recurso obtenemos todos los miembros del Congreso de los distintos grupos parlamentarios.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/member/" target=_blank>http://proyectocolibri.es/api/v1/member/</a></td>
          <td>Campos para filtrar: 
            <a href="http://proyectocolibri.es/api/v1/member/?id=1" target=_blank>id</a>, 
            <a href="http://proyectocolibri.es/api/v1/member/?name=Alberto" target=_blank>name</a>, 
            <a href="http://proyectocolibri.es/api/v1/member/?second_name=Alonso Ruiz" target=_blank>second_name</a>
          </td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/member/schema/">
        Detalle del recurso.
    </a>

    <h3>Listado de Miembros/partido</h3>
    <p>Con este recurso obtenemos todos los miembros del Congreso de los distintos grupos parlamentarios y el partido al que pertenecen.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/groupmember/" target=_blank>http://proyectocolibri.es/api/v1/groupmember/</a></td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/groupmember/schema/">
        Detalle del recurso.
    </a>

    <h3>Listado de Sesiones</h3>
    <p>Recurso para obtener las sesiones parlamentarias.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/session/" target=_blank>http://proyectocolibri.es/api/v1/session/</a></td>
          <td>
            <p>Campos para filtrar: 
                <a href="http://proyectocolibri.es/api/v1/session/?session=78" target=_blank>session</a>, 
                <a href="http://proyectocolibri.es/api/v1/session/?date=2012-06-19" target=_blank>date</a>
            </p>
            <p>Campos para ordenar: 
                <a href="http://proyectocolibri.es/api/v1/session/?order_by=-date" target=_blank>date</a>
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/session/schema/">
        Detalle del recurso.
    </a>

    <h3>Listado de Votoss</h3>
    <p>Recurso para obtener los votos de una determinada votacion en una sesion.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>http://proyectocolibri.es/api/v1/vote/</td>
          <td>Campos para filtrar: 
            <a href="http://proyectocolibri.es/api/v1/vote/?session_number=78&member=80&number=1" target=_blank>session_number, number, member</a>
          </td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/vote/schema/">
        Detalle del recurso.
    </a>

    <h3>Listado de Votos</h3>
    <p>Recurso para obtener todos los votos de todas las votaciones en todas las sesiones.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/vote_full/" target=_blank>http://proyectocolibri.es/api/v1/vote_full/</a></td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/vote_full/schema/">
        Detalle del recurso.
    </a>

    <h3>Listado de Votaciones</h3>
    <p>Recurso para obtener las votaciones de las sesiones.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/voting/" target=_blank>http://proyectocolibri.es/api/v1/voting/</a></td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/voting/schema/">
        Detalle del recurso.
    </a>


    <h3>Listado de Votaciones</h3>
    <p>Recurso para obtener las votaciones de las sesiones con los votos embebidos.</p>
    <table>
      <thead>
        <tr>
          <th>Url</th>
          <th>Parametros</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="http://proyectocolibri.es/api/v1/voting_full/" target=_blank>http://proyectocolibri.es/api/v1/voting_full/</a></td>
        </tr>
      </tbody>
    </table>
    <a href="http://proyectocolibri.es/api/v1/voting_full/schema/">
        Detalle del recurso.
    </a>

    </div>
  </div>
{% endblock %}

colibri/templates/main/example.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Proyecto Colibri</title>
  
  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->
  
  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="stylesheets/foundation.css">
  <link rel="stylesheet" href="stylesheets/app.css">

  <script src="javascripts/modernizr.foundation.js"></script>
  
  <!-- Included JS Files (Compressed) -->
  <script src="javascripts/jquery.js"></script>
  <script src="javascripts/foundation.min.js"></script>

</head>
<body>
  
  <!-- Header and Nav -->
  
  <div class="row">
    <div class="six columns">
      <h1>Proyecto Colibri</h1>
    </div>
    <div class="six columns">
      <ul class="nav-bar right">
        <li><a href="#">Link 1</a></li>
        <li><a href="#">Link 2</a></li>
        <li><a href="#">Link 3</a></li>
        <li><a href="#">Link 4</a></li>
      </ul>
    </div>
  </div>
  
  <!-- End Header and Nav -->
  
  
  <!-- First Band (Image) -->
    
  <div class="row">
    <div class="twelve columns">
      <img src="http://placehold.it/1000x400&text=[img]" />

    <br />
    <br />

      <form>
        <div class="row collapse">
          <div class="ten mobile-three columns">
            <input type="text" id="search-text" placeholder="Introduce tu busqueda" />
          </div>
          <div class="two mobile-one columns">
            <a id="search-button" class="button expand postfix">Buscar</a>
          </div>
        </div>
      </form>

      <hr />
    </div>
  </div>
  
  
  <!-- Second Band (Image Left with Text) -->
  
  <div class="row">
    <div class="four columns">
        <img src="http://placehold.it/400x300&text=[img]" />
    </div>
    <div class="eight columns">
      <h4>This is a content section.</h4>
      <div class="row">
		  <div class="six columns">
			<div id="sidebar">
			</div>
        </div>
      </div>
    </div>
  </div>
  
  
  <!-- Third Band (Image Right with Text) -->
  
  <div class="row">
    <div class="eight columns">
      <h4 id="content">This is a content section.</h4>
      
      <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
      
      <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
          
    </div>
    <div class="four columns">
      <img src="http://placehold.it/400x300&text=[img]" />
    </div>
  </div>
  
  
  <!-- Footer -->
  
  <footer class="row">
    <div class="twelve columns">
      <hr />
      <div class="row">
        <div class="six columns">
          <p>&copy; Copyright no one at all. Go to town.</p>
        </div>
        <div class="six columns">
          <ul class="link-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div> 
  </footer>

	<!-- Templates -->
	<script type="text/template" id="tpl-voting-list-item">
		<a href='#voting/<%= id %>'><%= id %></a>
	</script>

	<script type="text/template" id="tpl-voting-details">
		<div class="form-left-col">
			<label>Id:</label>
			<input type="text" id="votingId" name="id" value="<%= id %>" disabled />
		</div>
	</script>



  <!-- Included JS Files (Uncompressed) -->
  <!--
  
  <script src="javascripts/jquery.js"></script>
  
  <script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>
  
  <script src="javascripts/jquery.foundation.forms.js"></script>
  
  <script src="javascripts/jquery.foundation.reveal.js"></script>
  
  <script src="javascripts/jquery.foundation.orbit.js"></script>
  
  <script src="javascripts/jquery.foundation.navigation.js"></script>
  
  <script src="javascripts/jquery.foundation.buttons.js"></script>
  
  <script src="javascripts/jquery.foundation.tabs.js"></script>
  
  <script src="javascripts/jquery.foundation.tooltips.js"></script>
  
  <script src="javascripts/jquery.foundation.accordion.js"></script>
  
  <script src="javascripts/jquery.placeholder.js"></script>
  
  <script src="javascripts/jquery.foundation.alerts.js"></script>
  
  <script src="javascripts/jquery.foundation.topbar.js"></script>
  
  <script src="javascripts/jquery.foundation.joyride.js"></script>
  
  <script src="javascripts/jquery.foundation.clearing.js"></script>
  
  <script src="javascripts/jquery.foundation.magellan.js"></script>
  
  -->
  
    
  <!-- Initialize JS Plugins -->
  <script src="javascripts/app.js"></script>

  <!-- Backbone -->
  <script src="javascripts/backbone/underscore-min.js"></script>
  <script src="javascripts/backbone/backbone-min.js"></script>
  <script src="javascripts/backbone/backbone-tastypie.js"></script>
  <script src="javascripts/backbone/votings.js"></script>
</body>
</html>

colibri/templates/main/index.html
{% extends "base.html" %}

{% block links %}
{{ block.super }}
<link rel="stylesheet" type="text/css" media="screen" href="{{STATIC_URL}}main/stylesheets/coda-slider.css">
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{{STATIC_URL}}main/javascripts/jquery.coda-slider-3.0.js"></script>
{% endblock %}

{% block content %}
  <!-- First Band (Slider) -->
  <!-- The Orbit slider is initialized at the bottom of the page by calling .orbit() on #slider -->

  <div class="row">
    <div class="twelve columns">
      <!--<div id="slider">
        <img src="{{STATIC_URL}}main/images/proycolibri.gif" />
        <img src="{{STATIC_URL}}main/images/proycolibri.gif" />
        <img src="{{STATIC_URL}}main/images/proycolibri.gif" />
      </div>-->
      <div id="slider-info" class="coda-slider">
        <div class="info-box">
          <div class="row">
            <div class="four columns">
              <span class="entypo-box webicon xbig"></span>
            </div>
            <div class="eight columns right-text">
              <h1>Ordenamos para tí<br />los datos de Congreso.es</h1>
              <h4 class="white-text">Para que encuentres rapidamente lo que estás buscando</h4>
            </div>
          </div>
        </div>
        <div class="info-box">
          <div class="row">
            <div class="eight columns">
              <h1>Construye tu propia aplicación</h1>
              <h4 class="white-text">Te ofrecemos la posibilidad de que construyas tu propia aplicación haciendo uso de nuestra API con datos públicos</h4>
            </div>
            <div class="four columns">
              <span class="entypo-paper-plane webicon xbig"></span>
            </div>
          </div>
        </div>
        <div class="info-box">
          <div class="row">
            <div class="four columns">
              <span class="entypo-sound webicon xbig"></span>
            </div>
            <div class="eight columns">
              <h1>Apoya el Proyecto COLIBRI</h1>
              <h4 class="white-text">Haz lo que quieras o puedas: difunde el proyecto, solicita información específica, realiza visualizaciones o estudios con los datos de Congreso.es</h4>
            </div>
          </div>
        </div>
      </div>
      <hr />
      <p class="submain-text white-text center-text">El PROYECTO COLIBRI es una iniciativa ciudadana que pretende servir de puente entre la comunidad de programadores y periodistas y la web del Congreso del Gobierno de España para así facilitar el acceso a la información que en dicha web se puede encontrar.</p>
      <hr />
    </div>
  </div>


  <!-- Three-up Content Blocks -->

  <div class="row">

    <div class="four columns center-text">
      <span class="entypo-publish webicon big"></span>
      <!--<img src="{{STATIC_URL}}main/images/img.gif" />-->
      <h4>REST API</h4>
      <p>Ofrecemos una <a
        href="http://es.wikipedia.org/wiki/Interfaz_de_programaci%C3%B3n_de_aplicaciones"
        target="_blank">API</a> basada en servicios <a
        href="http://en.wikipedia.org/wiki/Representational_state_transfer"
        target="_blank">REST</a> para consumición de datos del Proyecto. Puedes
      encontrar más información en la <a href="{% url 'tastypie_swagger:documentation' %}">documentación oficial</a> del mismo.</p>
    </div>

    <div class="four columns center-text">
      <span class="entypo-chart-pie webicon big"></span>
      <h4>Visualización</h4>
      <p>Hemos desarrollado una aplicación web para consultar las votaciones del Congreso y queremos que sirva de base de futuros desarrollos que tanto nosotros como la comunidad pueda realizar.</p>
    </div>

    <div class="four columns center-text">
      <span class="entypo-code webicon big"></span>
      <h4>100% libre</h4>
      <p>Tan libre como un pájaro. Ponemos a disposición de la comunidad tanto el código fuente del servidor de datos como los extractores de información de la web del Congreso junto con la aplicación web de visualización de datos.</p>
    </div>

  </div>


  <!-- Call to Action Panel -->
  <div class="row">
    <div class="twelve columns">

      <div class="panel">
        <h4>Contacta con nosotros</h4>

        <div class="row">
          <div class="nine columns">
            <p>Hemos intentado lanzar una primera aproximación a las necesidades de información básicas de un ciudadano en relación con el Congreso de los Diputados. Seguiremos avanzando y para ello necesitamos de tu colabotación para proponer información a rescatar, ya sea para continuar un proyecto de investigación en el que andas trabajando, para el día a día de tu labor periodística o para realizar una visualización de datos. Nosotros sí queremos conocer tus necesidades en este sentido y queremos que ésto sirva de base de futuros desarrollos que tanto nosotros como la comunidad puedan realizar.</p>
          </div>
          <div class="three columns">
			  <a href="mailto:edipotrebol@gmail.com,azotillo@gmail.com,jneight@gmail.com?subject=ProyectoColibri" class="radius button right">Escríbenos</a>
			</div>
        </div>
      </div>

    </div>
  </div>
  {% endblock %}

{% block footerscript %}
{{ block.super }}
<!-- Put this above your </body> tag -->
<script type="text/javascript">
  $(window).load(function() {
    /*$('#slider').orbit({
	  animation: 'horizontal-push',                  // fade, horizontal-slide, vertical-slide, horizontal-push
	  animationSpeed: 1000,                // how fast animtions are
	  timer: true,                        // true or false to have the timer
	  resetTimerOnClick: false,           // true resets the timer instead of pausing slideshow progress
	  advanceSpeed: 4000,                 // if timer is enabled, time between transitions
	  pauseOnHover: false,                // if you hover pauses the slider
	  startClockOnMouseOut: false,        // if clock should start on MouseOut
	  startClockOnMouseOutAfter: 1000,    // how long after MouseOut should the timer start again
	  directionalNav: false,               // manual advancing directional navs
	  captions: false,                     // do you want captions?
	  captionAnimation: 'none',           // fade, slideOpen, none
	  captionAnimationSpeed: 1000,         // if so how quickly should they animate in
	  bullets: false,                     // true or false to activate the bullet navigation
	  bulletThumbs: false,                // thumbnails for the bullets
	  bulletThumbLocation: '',            // location from this file where thumbs will be
	  afterSlideChange: function(){},     // empty function
	  fluid: true                         // or set a aspect ratio for content slides (ex: '4x3')
	 });*/
    $('#slider-info').codaSlider({
      continuous: false,
      slideEaseDuration: '2000',
      autoSlide: true,
      autoHeight: false,
      dynamicArrows: false
    });
  });
</script>
{% endblock %}

colibri/templates/main/thanks.html
{% extends "base.html" %}
{% block content %}  
  <!-- Begin Contrib -->
  
  <div class="row">
    <div class="twelve columns">
      <h2>Agradecimientos</h2>
      <ul>
        <li><a href="https://www.djangoproject.com/" target="_blank">Django</a></li>
        <li><a href="http://tastypieapi.org" target="_blank">TastyPie</a></li>
        <li><a href="http://www.python.org" target="_blank">Python</a></li>
		    <li><a href="http://www.postgresql.org/" target="_blank">PostgreSQL</a></li>
        <li><a href="http://foundation.zurb.com" target="_blank">Foundation</a></li>
        <li><a href="http://weloveiconfonts.com" target="_blank">We love icon fonts</a></li>
        <li><a href="https://github.com/KevinBatdorf/codaslider" target="_blank">Coda Slider</a></li>
		    <li><a href="http://git-scm.com/" target="_blank">Git</a></li>
        <li><a href="http://github.com/" target="_blank">Github</a></li>
        <li>Datos obtenidos de Congreso.es</li>
      </ul>
      <p>Mencion especial para <a href="http://kadozkreaccion.es" target="_blank">KadozKreaccion</a> por la identidad grafica del proyecto.</p>
    </div>

  <!-- End Contrib -->

{% endblock %}